version: '3.1'

services:
  dbservice:
    image: mysql
    
    environment:
     - MYSQL_ROOT_PASSWORD= root
     - MYSQL_PASSWORD= root
     - DATABASE_PORT= 3306
     - DATABASE_HOST= docker.mysql
    networks:
     - restroNetwork
   
  appservice:
    image: restro
    build: .
    depends_on:
     - dbservice
    environment:
     - spring.datasource.url= jdbc:mysql://dbservice:3307/restrodb?createDatabaseIfNotExist=true
     - spring.datasource.username= admin
     - spring.datasource.password= root
    ports:
     - 9696:8686
    networks:
     - restroNetwork
     
networks:
  restroNetwork:
  
  